environment: dev

data:
  deployment:
    name: mssql-deployment
    pod:
      name: mssql
      securityContext:
        fsGroup: 10001
      initContainer:
        image:
          name: kecoacr.azurecr.io/adventureworks2017-mssql2019-ubuntu16.04-backup-only:1.0
          pullPolicy: Always
      container:
        image:
          name: mcr.microsoft.com/mssql/server:2019-CU2-ubuntu-16.04
        containerPort: 1433
  secret:
    name: mssql-login
    values:
      SA_PASSWORD: TXlDMG05bCZ4UEBzc3cwcmQ=
      WEB_API_LOGIN: V2ViQXBpTG9naW4=
      WEB_API_LOGIN_PASSWORD: PzhkNUViRFV+antfRWFd
      WEB_API_LOGIN_USER: V2ViQXBpVXNlcg==
  service:
    name: mssql-service
    port: 1433
  sql:
    database:
      name: AdventureWorks2017
      mssqlPath: /var/opt/mssql

pvc:
  name: mssql-data
  storage: 10Gi

api:
  deployment:
    name: dotnet-api-deployment
    pod:
      replicas: 3
      name: dotnet-api
      initContainer:
        image:
          name: busybox
      container:
        image:
          name: kecoacr.azurecr.io/adventureworks-api-dotnet3.1:1.0
          pullPolicy: Always
        containerPort: 80
  secret:
    name: api-appsettings
    values:
      appSettingsJson: ew0KICAiTG9nZ2luZyI6IHsNCiAgICAiTG9nTGV2ZWwiOiB7DQogICAgICAiRGVmYXVsdCI6ICJJbmZvcm1hdGlvbiIsDQogICAgICAiTWljcm9zb2Z0IjogIldhcm5pbmciLA0KICAgICAgIk1pY3Jvc29mdC5Ib3N0aW5nLkxpZmV0aW1lIjogIkluZm9ybWF0aW9uIg0KICAgIH0NCiAgfSwNCiAgIkFsbG93ZWRIb3N0cyI6ICIqIg0KfQ0K
  service:
    name: dotnet-api-service
    port: 80
  dotnet:
    api:
      appSettingsPath: /app/settings

app:
  deployment:
    name: dotnet-app-deployment
    pod:
      replicas: 5
      name: dotnet-app
      initContainer:
        image:
          name: busybox
      container:
        image:
          name: kecoacr.azurecr.io/adventureworks-app-dotnet3.1:1.0
          pullPolicy: Always
        containerPort: 80
  configMap:
    name: app-env-config
    values:
      appEnvConfig: 
  service:
    name: dotnet-app-service
    port: 80
  dotnet:
    app:
      envPath: /app/ClientApp/dist
