apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: sql-backup
          image: kecoacr.azurecr.io/wwi-mssql2019-ubuntu16.04:1.0
          command: 
            - sh
            - -c
          args:
            -  |
              if [ -z "$(ls -A /data)" ]; then
                echo "MSSQL volume empty.  Copying backup."
                cp -r /var/opt/mssql/data/ /data
                echo "Backup data copied"
              else
                echo "MSSQL volume not empty.  Skipping backup."
              fi
          volumeMounts:
            - name: mssqldb
              mountPath: /data
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-CU2-ubuntu-16.04
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD 
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  #type: LoadBalancer
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
