apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.data.deployment.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.data.deployment.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.data.deployment.pod.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.data.deployment.pod.name }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/component: data
    spec:
      securityContext:
        fsGroup: {{ .Values.data.deployment.pod.securityContext.fsGroup }}
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: sql-backup
          image: {{ .Values.data.deployment.pod.initContainer.image.name }}
          imagePullPolicy: {{ .Values.data.deployment.pod.initContainer.image.pullPolicy }}
          command: 
            - sh
            - -c
          args:
            -  |
              if [ ! -d "/data/data" ]; then
                echo "MSSQL data doesn't exist. Copying backup."
                cp -r {{ .Values.data.sql.database.mssqlPath }}/data/ /data
                echo "Backup data copied"
              else
                echo "MSSQL data exists. Skipping backup."
              fi
          volumeMounts:
            - name: mssqldb
              mountPath: /data
      containers:
        - name: mssql
          image: {{ .Values.data.deployment.pod.container.image.name }}
          ports:
            - containerPort: {{ .Values.data.deployment.pod.container.containerPort }}
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
          envFrom:
            - secretRef:
                name: {{ .Values.data.secret.name }}
          volumeMounts:
            - name: mssqldb
              mountPath: {{ .Values.data.sql.database.mssqlPath }}
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    LOGIN_EXISTS=$(/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "$SA_PASSWORD" -Q "SELECT sp.name FROM sys.server_principals sp LEFT JOIN sys.sql_logins sl ON sp.principal_id = sl.principal_id WHERE sp.name = '$WEB_API_LOGIN'" | grep "$WEB_API_LOGIN")
                    if [ -z "$LOGIN_EXISTS" ]; then
                      echo "Login doesn't exist.  Creating login."
                      /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "$SA_PASSWORD" -Q "CREATE LOGIN $WEB_API_LOGIN WITH PASSWORD = '$WEB_API_LOGIN_PASSWORD'"
                      /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "$SA_PASSWORD" -Q "
                      Use AdventureWorks2017;
                      GO
                      IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'$WEB_API_LOGIN_USER')
                      BEGIN
                          CREATE USER $WEB_API_LOGIN_USER FOR LOGIN $WEB_API_LOGIN
                          EXEC sp_addrolemember N'db_owner', N'$WEB_API_LOGIN_USER'
                      END;
                      GO"
                      echo "Login created."
                    else
                      echo "Login exists. Skipping creation."
                    fi
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.data.service.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.data.service.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: data
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.data.deployment.pod.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.data.service.port }}
      targetPort: {{ .Values.data.deployment.pod.container.containerPort }}
