apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.pvc.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
