apiVersion: v1
data:
  SA_PASSWORD: TXlDMG05bCZ4UEBzc3cwcmQ=
  WEB_API_LOGIN: V2ViQXBpTG9naW4=
  WEB_API_LOGIN_PASSWORD: PzhkNUViRFV+antfRWFd
  WEB_API_LOGIN_USER: V2ViQXBpVXNlcg==
kind: Secret
metadata:
  creationTimestamp: null
  name: mssql-login
