apiVersion: v1
data:
  {{ .Values.certManager.secret.key }}: {{ .Values.certManager.secret.values.CERT_MANAGER_CLIENT_SECRET }}
kind: Secret
metadata:
  name: {{ .Values.certManager.secret.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.certManager.secret.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
