apiVersion: v1
data:
  SA_PASSWORD: {{ .Values.data.secret.values.SA_PASSWORD }}
  WEB_API_LOGIN: {{ .Values.data.secret.values.WEB_API_LOGIN }}
  WEB_API_LOGIN_PASSWORD: {{ .Values.data.secret.values.WEB_API_LOGIN_PASSWORD }}
  WEB_API_LOGIN_USER: {{ .Values.data.secret.values.WEB_API_LOGIN_USER }}
kind: Secret
metadata:
  name: {{ .Values.data.secret.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.data.secret.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
