PROVIDER: azure
LOCATION: eastus
TERRAFORM_BACKEND_GROUP_NAME: k-eco-terraform
STORAGE_ACCOUNT_NAME: kecoterraform
STORAGE_CONTAINER_NAME: terraform
STORAGE_CONTAINER_KEY: prod-terraform.tfstate
GROUP_NAME: k-eco-prod
CLUSTER_NAME: k-cluster-prod
ACR_NAME: kecoacrprod
CERT_ACME_SERVER: https://acme-v02.api.letsencrypt.org/directory
SQL_IMAGE_NAME: adventureworks2017-mssql2019-ubuntu16.04-backup-only
SQL_IMAGE_VERSION: 1.0
API_IMAGE_NAME: adventureworks-api-dotnet3.1
API_IMAGE_VERSION: 1.0
APP_IMAGE_NAME: adventureworks-app-dotnet3.1
APP_IMAGE_VERSION: 1.0
HELM_INSTALL_NAME: adventureworks
