apiVersion: v1
data:
  appsettings.json: {{ .Values.api.secret.values.appSettingsJson }}
kind: Secret
metadata:
  name: {{ .Values.api.secret.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.api.secret.name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
