apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.postInstall.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.postInstall.name | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Values.postInstall.name }}
      labels:
        app.kubernetes.io/name: {{ .Values.postInstall.name | quote }}
        app.kubernetes.io/part-of: {{ .Release.Name | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      restartPolicy: Never
      containers:
        - name: login-setup
          image: {{ .Values.postInstall.image.name }}
          command: 
            - sh
            - -c
          args:
            -  |
              LOGIN_EXISTS=$(/opt/mssql-tools/bin/sqlcmd -S {{ .Values.data.service.name }} -U SA -P "$SA_PASSWORD" -Q "SELECT sp.name FROM sys.server_principals sp LEFT JOIN sys.sql_logins sl ON sp.principal_id = sl.principal_id WHERE sp.name = '$WEB_API_LOGIN'" | grep "$WEB_API_LOGIN")
              if [ -z "$LOGIN_EXISTS" ]; then
                echo "Login doesn't exist.  Creating login."
                /opt/mssql-tools/bin/sqlcmd -S {{ .Values.data.service.name }} -U SA -P "$SA_PASSWORD" -Q "CREATE LOGIN $WEB_API_LOGIN WITH PASSWORD = '$WEB_API_LOGIN_PASSWORD'"
                /opt/mssql-tools/bin/sqlcmd -S {{ .Values.data.service.name }} -U SA -P "$SA_PASSWORD" -Q "
                Use AdventureWorks2017;
                GO
                IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'$WEB_API_LOGIN_USER')
                BEGIN
                    CREATE USER $WEB_API_LOGIN_USER FOR LOGIN $WEB_API_LOGIN
                    EXEC sp_addrolemember N'db_owner', N'$WEB_API_LOGIN_USER'
                END;
                GO"
              else
                echo "Login exists. Skipping creation."
              fi
          envFrom:
            - secretRef:
                name: {{ .Values.data.secret.name }}
