name: cleanup

on:
  watch:
    types: [started]

jobs:
  authorize: 
    runs-on: ubuntu-latest

    steps:
      - uses: octokit/request-action@v2.0.0
        with:
          route: GET /repos/:repository/collaborators/${{ github.actor }}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    needs: [authorize]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script file
        env:
          GROUP_NAME: k-eco
        uses: azure/CLI@v1
        with:
          azcliversion: 2.4
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/azure/azure-cleanup.sh
            $GITHUB_WORKSPACE/azure/azure-cleanup.sh -g $GROUP_NAME
