name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  infra:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.4
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/azure/azure-setup.sh
          $GITHUB_WORKSPACE/azure/azure-setup.sh
