name: infrastructure

on:
  push:
    branches:
      - master

jobs:
  azure:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI script file
      env:
        GROUP_NAME: k-eco
        LOCATION: eastus
        CLUSTER_NAME: k-cluster
        DOMAIN_NAME: ${{ secrets.PUBLIC_DOMAIN_NAME }}
        ACRNAME: kecocr
      uses: azure/CLI@v1
      with:
        azcliversion: 2.4
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/azure/azure-setup.sh
          $GITHUB_WORKSPACE/azure/azure-setup.sh -g $GROUP_NAME -l $LOCATION -n $CLUSTER_NAME --domain-name $DOMAIN_NAME --acr-name $ACRNAME
