#name: Default Bash
#on: [push]
#
#jobs:
#  test:
#
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, macos-latest]
#    steps:
#
#      - name: No shell specified (default bash)
#        run: echo Hello, world!
#
#      - name: Shell specified as bash
#        run: echo Hello, world!
#        shell: bash
